#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: c1050fe
#
Name     : R-tensorA
Version  : 0.36.2.1
Release  : 53
URL      : https://cran.r-project.org/src/contrib/tensorA_0.36.2.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/tensorA_0.36.2.1.tar.gz
Summary  : Advanced Tensor Arithmetic with Named Indices
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: R-tensorA-lib = %{version}-%{release}
Requires: R-tensorA-license = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
linear algebra with tensors and computation with data sets of
        tensors on a higher level abstraction. It includes Einstein and
        Riemann summing conventions, dragging, co- and contravariate
        indices, parallel computations on sequences of tensors.

%package lib
Summary: lib components for the R-tensorA package.
Group: Libraries
Requires: R-tensorA-license = %{version}-%{release}

%description lib
lib components for the R-tensorA package.


%package license
Summary: license components for the R-tensorA package.
Group: Default

%description license
license components for the R-tensorA package.


%prep
%setup -q -n tensorA
pushd ..
cp -a tensorA buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702950157

%install
export SOURCE_DATE_EPOCH=1702950157
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-tensorA
cp %{_builddir}/tensorA/COPYING %{buildroot}/usr/share/package-licenses/R-tensorA/075d599585584bb0e4b526f5c40cb6b17e0da35a || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/tensorA/DESCRIPTION
/usr/lib64/R/library/tensorA/INDEX
/usr/lib64/R/library/tensorA/Meta/Rd.rds
/usr/lib64/R/library/tensorA/Meta/features.rds
/usr/lib64/R/library/tensorA/Meta/hsearch.rds
/usr/lib64/R/library/tensorA/Meta/links.rds
/usr/lib64/R/library/tensorA/Meta/nsInfo.rds
/usr/lib64/R/library/tensorA/Meta/package.rds
/usr/lib64/R/library/tensorA/NAMESPACE
/usr/lib64/R/library/tensorA/R/tensorA
/usr/lib64/R/library/tensorA/R/tensorA.rdb
/usr/lib64/R/library/tensorA/R/tensorA.rdx
/usr/lib64/R/library/tensorA/help/AnIndex
/usr/lib64/R/library/tensorA/help/aliases.rds
/usr/lib64/R/library/tensorA/help/paths.rds
/usr/lib64/R/library/tensorA/help/tensorA.rdb
/usr/lib64/R/library/tensorA/help/tensorA.rdx
/usr/lib64/R/library/tensorA/html/00Index.html
/usr/lib64/R/library/tensorA/html/R.css
/usr/lib64/R/library/tensorA/tests/checker.R
/usr/lib64/R/library/tensorA/tests/examples.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/tensorA/libs/tensorA.so
/usr/lib64/R/library/tensorA/libs/tensorA.so.avx2
/usr/lib64/R/library/tensorA/libs/tensorA.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-tensorA/075d599585584bb0e4b526f5c40cb6b17e0da35a
